# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2
cache: bundler

before_script:
  - export LANG=en_US.UTF-8

install:
  - bundle install
  - bundle exec pod install
  - make ci

script:
  - make test
