workspace 'ARCollectionViewMasonryLayout'

target "ARCollectionViewMasonryLayoutTests" do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta', '~> 0.2.3'
  pod 'FBSnapshotTestCase', '~> 1.1'
  pod 'EXPMatchers+FBSnapshotTest', '~> 1.0'
end

